set_temperature:
  description: Set smoker temperature setpoint.
  fields:
    temperature: 
      description: 'New setpoint temperature'
      example: '225'
set_alarms:
  description: Set smoker alarms.
  fields:
    alarms: 
      description: 'New alarm temperatures'
      example: '-190,-250,-100,-205,-100,-100,-100,-100'